// eslint-disable-next-line react/no-children-prop

import localFont from "next/font/local";
import "./globals.css";
import SideBarMenu from "@/components/SideBarMenu";
import Provider from "@/components/Provider";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <ToastContainer/>
          <SideBarMenu>{children}</SideBarMenu>
        </Provider>
      </body>
    </html>
  );
}
